completed signup page
Adarsh-Patel-Dev/E-commerce-App pull request #1
Opened 2022-02-16 21:37 UTC by Adarsh-Patel-Dev

![image](https://user-images.githubusercontent.com/81930207/154361194-d040c1f3-5b43-45e2-8f57-6ac3a45197d5.png)

2022-02-16 22:03 UTC, swastika0015 commented
The nav items on right are not displaying to the extreme right on my screen.
This is how it's looking.

![Capture11](https://user-images.githubusercontent.com/44317853/154364961-fcd19a6e-a76f-48e9-a52c-08cbd39fe099.PNG)

2022-02-17 05:36 UTC, sri-rishi requested changes
Be consistent with units like for units more than 1rem use rems and otherwise use px

2022-02-17 05:36 UTC, sri-rishi commented on index.css
> +    /* width: ; */
remove comments

2022-02-17 05:36 UTC, sri-rishi commented on index.css
> +    background: rgba(255, 255, 255, 0.11);
use variable color naming

2022-02-17 05:36 UTC, sri-rishi commented on index.css
> +    height: 500px;
can use rem here

2022-02-17 05:36 UTC, sri-rishi commented on index.css
> +    box-shadow: 0px 0px 100px rgba(255, 255, 255, 0.25);
You can use just 0 instead of 0px, it will work same

2022-02-17 05:36 UTC, sri-rishi commented on index.html
> +
remove extra spacing in code

2022-02-17 05:36 UTC, sri-rishi commented on index.html
> +    <div class="nav-bar">
for navigation use navbar tag

2022-02-17 12:54 UTC, Adarsh-Patel-Dev commented
> The nav items on right are not displaying to the extreme right on my screen. This is how it's looking.
> 
> ![Capture11](https://user-images.githubusercontent.com/44317853/154364961-fcd19a6e-a76f-48e9-a52c-08cbd39fe099.PNG)

fixed it

2022-02-17 12:54 UTC, Adarsh-Patel-Dev commented on index.css
> +    /* width: ; */
done

2022-02-17 12:57 UTC, merged